<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KeywordSeeder extends Seeder
{
    private $keywords = [
        [1,"support group"],
        [2,"dual identity"],
        [3,"nihilism"],
        [4,"rage and hate"],
        [5,"insomnia"],
        [6,"dystopia"],
        [7,"violence"],
        [8,"amityville horror"],
        [9,"prequel"],
        [10,"evil doll"],
        [11,"spin off"],
        [12,"demonic possession"],
        [13,"berlin"],
        [14,"spy"],
        [15,"undercover"],
        [16,"cold war"],
        [17,"double agent"],
        [18,"undercover agent"],
        [19,"based on comic book"],
        [20,"murder"],
        [21,"mi6"],
        [22,"murder investigation"],
        [23,"cgi"],
        [24,"anthropomorphism"],
        [25,"dc comics"],
        [26,"hero"],
        [27,"greek mythology"],
        [28,"island"],
        [29,"world war i"],
        [30,"superhero"],
        [31,"superheroine"],
        [32,"period drama"],
        [33,"heroine"],
        [34,"super powers"],
        [35,"woman director"],
        [36,"1910s"],
        [37,"dc extended universe"],
        [38,"beach"],
        [39,"drug dealer"],
        [40,"based on tv series"],
        [41,"lifeguard"],
        [42,"rookie"],
        [43,"vigilantism"],
        [44,"france"],
        [45,"world war ii"],
        [46,"evacuation"],
        [47,"german"],
        [48,"pilot"],
        [49,"british army"],
        [50,"royal navy"],
        [51,"royal air force"],
        [52,"private"],
        [53,"allied forces"],
        [54,"app"],
        [55,"emoji"],
        [56,"smartphone"],
        [57,"minions"],
        [58,"miami"],
        [59,"dark comedy"],
        [60,"male stripper"],
        [61,"bachelorette party"],
        [62,"gunslinger"],
        [63,"based on novel"],
        [64,"sea"],
        [65,"ship"],
        [66,"sequel"],
        [67,"artifact"],
        [68,"pirate"],
        [69,"swashbuckler"],
        [70,"ghost"],
        [71,"caribbean"],
        [72,"talking animal"],
        [73,"ape"],
        [74,"threequel"],
        [75,"new york"],
        [76,"high school"],
        [77,"marvel comic"],
        [78,"teenager"],
        [79,"reboot"],
        [80,"marvel cinematic universe"],
        [81,"squirrel"],
        [82,"shapeshifting"],
        [83,"future"],
        [84,"utopia"],
        [85,"space travel"],
        [86,"diversity"],
        [87,"alien"],
        [88,"alien planet"],
        [89,"independent film"],
        [90,"energy"],
        [91,"alien abduction"],
        [92,"genocide"],
        [93,"political intrigue "],
        [94,"pacifist"],
        [95,"space opera"],
        [96,"military"],
        [97,"government agent"],
        [98,"marketplace"],
        [99,"trapped in space"],
        [100,"federal government"],
        [101,"unity"],
        [102,"parallel dimension"],
        [103,"cosmopolis"],
        [104,"robbery"],
        [105,"atlanta"],
        [106,"musical"],
        [107,"music"],
        [108,"crime boss"],
        [109,"romance"],
        [110,"tinnitus"],
        [111,"car chase"],
        [112,"car"],
        [113,"getaway driver"]
    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach($this->keywords as $keyword)
        {
            DB::table('keywords')->insert([
                'id' => $keyword[0],
                'name' => $keyword[1],
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString()
            ]);
        }
    }
}
